%% Returns the open-circuit voltage given the SOC using the polyfit done
function U_oc = SOCtoUoc(SOC, batpack)
    U_oc = batpack.polyfitCoefficients(1) .* SOC.^3 + ...
    batpack.polyfitCoefficients(2) .* SOC.^2 + ...
    batpack.polyfitCoefficients(3) .* SOC + ...
    batpack.polyfitCoefficients(4);
end

