function [dX, constraints, signals, param] = liu_diesel_NOx(X, U, param)
% LIU_DIESEL_2 - A mean value model of a heavy-duty diesel engine
% ---------------------------------------------------------------------
% MVEM LiU Diesel 2.0
% [dX, constraints, signals] = liu_diesel_2(X, U, N_ice, param)
% x = [p_caf, p_im, p_em, n_turb]'
% u = [Ne, u_delta, u_thr, u_wg]'
%
% ---------------------------------------------------------------------
%% States
p_cac   = X(1,:); % Charge air cooler pressure [Pa]
p_im   	= X(2,:); % Intake manifold pressure [Pa]
p_em  	= X(3,:); % Exhaust manifold pressure [Pa]
w_t  	= X(4,:); % Turbocharger angular velocity [rad/s]
NOx_tot	= X(5,:); % NOx [g]
N_ice   = X(6,:); % Engine speed [rpm]

% Control signals
u_f     = U(1,:); % Fuel injection per unit cycle [mg/cyc]
u_thr   = U(2,:); % Throttle position [0, 1]
u_wg    = U(3,:); % Wastegate position [0, 1]

%% Unit conversions
Nt      = w_t./(2*pi); % Turbocharger speed [rps]
W_f     = (1e-6/120).*u_f.*N_ice.*param.n_cyl; % Fuel massflow [kg/s]
P_f     = W_f .* param.q_HV;

%% Compressor
[W_comp, eta_comp, T_comp, P_comp, comp_constraints] ...
        = compressor(param.p_amb, p_cac, param.T_amb, w_t, param.comp);
Pi_comp = p_cac./param.p_amb; % Compressor pressure ratio [-]

%% Intake manifold
eta_vol = volumetric_efficiency(p_im, N_ice, param); % [-]
W_cyl   = W_cylinder(eta_vol, p_im, param.T_im, N_ice, param); % cylinder massflow [kg/s]

%% Cylinder
[M_ice, cyl_sig] = engine_torque(N_ice, p_im, p_em, u_f, param); % [Nm]
T_em    = T_cyl_out(p_im, p_em, param.T_im, W_f, W_cyl, param); % [K]
P_ice   = M_ice .* N_ice * pi/30; % [W]
phi     = param.AFs * W_f ./ W_cyl; % Fuel-to-air equivalence ratio [-]
eta_f   = P_ice./(W_f * param.q_HV);

%% Throttle
[W_thr, ~, Pi_thr] = W_throttle(p_cac, p_im, param.T_cac, u_thr, param); % Throttle massflow [kg/s]

%% Turbine & Wastegate
% Turbine
Pi_turb = param.p_amb./p_em; % [-]
W_t_corr = turbine_massflow(Pi_turb, 60.*Nt./sqrt(T_em), param);
W_turb  = p_em./1e3./sqrt(T_em) .* W_t_corr; % [kg/s]
BSR     = turbine_BSR(Pi_turb, w_t, T_em, param); % [-]
eta_tm  = turbine_efficiency(BSR, (Nt.*60)/sqrt(T_em), param); % [-]
T_at    = turbine_T(Pi_turb, T_em, eta_tm, param); % [K]

% Wastegate
W_wg          = W_wastegate(p_em, param.p_amb, T_em, u_wg, param); % [kg/s]
P_turb_eta_tm = turbine_power(W_turb, T_em, Pi_turb, eta_tm, param); % [W]
T_wg          = T_em;%wastegate_T(Pi_turb, T_em, param.gamma_cyl);

% After Turbine and Wastegate
W_tw        = W_wg + W_turb;
T_atw       = mix_wg_t(W_turb, W_wg, T_at, T_wg);
T_tw_drop   = T_em - T_atw;


%% Emission
lut_NOx     = param.lut_NOx;
%lut_NO      = param.lut_NO;
%lut_NO2NO   = param.lut_NO2NO;

NOx_EO     = full(lut_NOx([N_ice M_ice]));       % [g/s]
%NO2NO   = full(lut_NO2NO([N_ice M_ice]));     % [-]
%NO      = full(lut_NO([N_ice M_ice]));        % [ppm]
%NO2     = NO2NO .* NO;                        % [ppm]
%NOx     = NO + NO2;                           % [ppm]
%NO2NOx  = NO2 ./ NOx .* 100;                  % [%]

%% Dynamics
dpcaf = param.R_a .* T_comp .* (W_comp - W_thr) ./ param.V_cac;
dpim  = param.R_a .* param.T_amb .* (W_thr - W_cyl) ./ param.V_im;
dpem  = param.R_e .* T_em .* (W_cyl + W_f - W_turb - W_wg) ./ param.V_em;
dwtc  = (P_turb_eta_tm - P_comp) ./ (w_t .* param.J_tc);
%dNOx  = NOx;
dX    = [dpcaf; dpim; dpem; dwtc];%; dNOx];

%% Constraints
constraints = [...
    phi-1/param.lambda_min; ...
    param.BSR_min - BSR; ...
    BSR - param.BSR_max; ...
    p_im - p_cac; ...
    param.turb.c_m2 - w_t; ...
    param.constr.P_ice_max_fn(P_ice, N_ice); ...
    %600 - T_at; ...    % Minimal temp
    %T_at - 900;         % Maximal temp
    param.constr.torque_max_fn(N_ice, M_ice); ...
    comp_constraints ...
    ];

%% Signals
signals=struct(...
    ... CAC and Throttle
    'p_cac'   ,p_cac  , ...
    'W_thr'   ,W_thr  , ...
    'u_thr'   ,u_thr  , ...
    'Pi_thr'  ,Pi_thr , ...
    ... Intake manifold
    'p_im'    ,p_im   , ...
    'W_cyl'   ,W_cyl  , ...
    'eta_vol' ,eta_vol, ...
    ... Cylinder
    'N_ice'   ,N_ice  , ...
    'M_ice'   ,M_ice  , ...
    'P_ice'   ,P_ice  , ...
    'u_f'     ,u_f    , ...
    'W_f'     ,W_f    , ...
    'P_f'     ,P_f    , ...
    'Lambda'  ,1./phi , ...
    'phi'     ,phi    , ...
    'eta_f'   ,eta_f  , ...
    'M_fric'  ,cyl_sig.M_fric, ...
    'M_pump'  ,cyl_sig.M_pump, ...
    'M_ig'    ,cyl_sig.M_ig, ...
    ... Exhaust manifold
    'p_em'    ,p_em   , ...
    'T_em'    ,T_em   , ...
    ... Turbo
    'w_t'     ,w_t    , ...
    'N_t'     ,w_t*30/pi/1e3, ... [krpm]
    'eta_tm'  ,eta_tm , ...
    ... Turbine
    'Pi_turb' ,Pi_turb, ...
    'W_wg'    ,W_wg   , ...
    'u_wg'    ,u_wg   , ...
    'W_turb'  ,W_turb , ...
    'BSR'     ,BSR    , ...
    'P_turb_eta_tm', P_turb_eta_tm, ... 
    'T_turb'    ,T_at   , ...
    'T_turb_drop' ,T_em-T_at , ...
    ... Compressor
    'Pi_comp' ,Pi_comp, ...
    'W_comp'  ,W_comp , ...
    'eta_comp',eta_comp, ...
    'T_comp'  ,T_comp , ...
    'P_comp'  ,P_comp, ...
    ... After Turbine and Wastegate
    'T_atw'   ,T_atw, ...
    'T_tw_drop' ,T_tw_drop, ...
    'W_tw'    ,W_tw, ...
    ... Enging out Emissions
    ... 'NO2'     ,NO2, ...
    ... 'NO'      ,NO, ...
    'NOx_EO'     ,NOx_EO, ...
    ... 'NO2NOx'  ,NO2NOx, ...    
    'NOx_tot' ,NOx_tot ...
    );
% if ~isreal(dX)
% end
end