function render_engine_map(engine_map, line_grid, line_text_size, axis_text_size, text_spacing, xaxis_text, yaxis_text, title_text)

[C, h] = contourf( ...
    engine_map.rpm_grid, ...
    engine_map.torque_grid, ...
    engine_map.efficiency_grid, ...
    line_grid, ...
    'ShowText','on', ...
    'LabelSpacing', text_spacing ...
    );
clabel(C, h, 'FontSize', line_text_size);
% colormap lines
plt = gca;
plt.FontSize = axis_text_size;
plot(engine_map.rpm_range, engine_map.torque_grid(end,:), 'r-', 'LineWidth', 2)

xlabel(xaxis_text)
ylabel(yaxis_text)
title(title_text)


end